# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='send_new_post_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[(b'POST_AUTHOR', b'post_author'), (b'PARENT_COMMENT_AUTHOR', b'comment_parent_author'), (b'MENTIONED_USER', b'mentioned_user')], max_length=30),
        ),
    ]
