# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('direction', models.IntegerField(choices=[(1, 1), (-1, -1), (0, 0)], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvoted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvoted_by',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.Comment'),
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.Post'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.Account'),
        ),
    ]
