# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190119_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[(b'POST_AUTHOR', b'post_author'), (b'PARENT_COMMENT_AUTHOR', b'comment_parent_author'), (b'MENTIONED_USER', b'mentioned_user'), (b'USER_POSTED_IN_SUB', b'user_posted_in_sub')], max_length=30),
        ),
    ]
