# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190218_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 2, 19, 1, 15, 1, 858756)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_comments', to='app.Account'),
        ),
    ]
