# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body_text',
        ),
        migrations.AddField(
            model_name='post',
            name='body_html',
            field=models.TextField(default='some text'),
            preserve_default=False,
        ),
    ]
