# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit_clone_django_rest', '0002_auto_20181118_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit_clone_django_rest.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit_clone_django_rest.Post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
