# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(null=True),
        ),
    ]
