# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0008_auto_20181118_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_in',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='reddit_clone_django_rest.Sub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='admins',
            field=models.ManyToManyField(to='reddit_clone_django_rest.Account'),
        ),
        migrations.AddField(
            model_name='sub',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='reddit_clone_django_rest.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='posts',
            field=models.ManyToManyField(to='reddit_clone_django_rest.Post'),
        ),
        migrations.AddField(
            model_name='sub',
            name='subscribers',
            field=models.ManyToManyField(to='reddit_clone_django_rest.Account'),
        ),
    ]
