# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0010_auto_20181118_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='admin_of',
            field=models.ManyToManyField(blank=True, to='reddit_clone_django_rest.Sub'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subs',
            field=models.ManyToManyField(blank=True, to='reddit_clone_django_rest.Sub'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='admins',
            field=models.ManyToManyField(blank=True, to='reddit_clone_django_rest.Account'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='posts',
            field=models.ManyToManyField(blank=True, to='reddit_clone_django_rest.Post'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to='reddit_clone_django_rest.Account'),
        ),
    ]
