# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0011_auto_20181118_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sub',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
