# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0012_auto_20181118_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='admin_of',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subs',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='posts',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='reddit_clone_django_rest.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reddit_clone_django_rest.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_in',
            field=models.ManyToManyField(related_name='posts', to='reddit_clone_django_rest.Sub'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_of', to='reddit_clone_django_rest.Account'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subs', to='reddit_clone_django_rest.Account'),
        ),
    ]
