# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0013_auto_20181118_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subs_created', to='reddit_clone_django_rest.Account'),
        ),
    ]
