# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0014_auto_20181118_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
