# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0015_post_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saved_comments',
            field=models.ManyToManyField(related_name='saved_by', to='reddit_clone_django_rest.Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by', to='reddit_clone_django_rest.Post'),
        ),
    ]
