# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0018_auto_20181121_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='saved_comments',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_posts',
        ),
        migrations.AddField(
            model_name='comment',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_comments', to='reddit_clone_django_rest.Account'),
        ),
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_posts', to='reddit_clone_django_rest.Account'),
        ),
    ]
