# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0019_auto_20181121_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='downvoted_posts', to='reddit_clone_django_rest.Account'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted_posts', to='reddit_clone_django_rest.Account'),
        ),
        migrations.AddField(
            model_name='post',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='downvoted_posts', to='reddit_clone_django_rest.Account'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted_posts', to='reddit_clone_django_rest.Account'),
        ),
    ]
