# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0021_auto_20181123_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_in',
        ),
        migrations.AddField(
            model_name='post',
            name='posted_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='reddit_clone_django_rest.Sub'),
            preserve_default=False,
        ),
    ]
