# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0022_auto_20181124_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
    ]
