# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0023_auto_20181124_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reddit_clone_django_rest.Account'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='reddit_clone_django_rest.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_posts', to='reddit_clone_django_rest.Account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_posts', to='reddit_clone_django_rest.Account'),
        ),
    ]
