# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0026_post_hotness'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='confidence',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
