# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0027_comment_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
