# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0028_auto_20181130_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(),
        ),
    ]
