# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0029_auto_20181130_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='link_previews/'),
        ),
    ]
