# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0030_post_link_preview_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
