# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0031_auto_20181201_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='sub',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
