# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0032_auto_20181202_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
