# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0033_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_comments', to='reddit_clone_django_rest.Account'),
        ),
    ]
