# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-12 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone_django_rest', '0034_auto_20181202_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hotness',
        ),
    ]
